### ISSUE TITLE
Accessibility: Show ASL player

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#308] opened 2022-01-05 21:02 UTC

**Comment by cherylhjli** [comment] 2022-08-02 20:22
Can turn it on in the web accessibility preferences page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2265%3A74852

In-page it will show up as a button you can click to open and close the videos: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2327%3A63742
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2327%3A62233

**Comment by greatislander** [comment] 2022-08-03 17:41
Duplicate of #496.

**Closed** 2022-08-03 17:42 UTC
Labels: enhancement
