### ISSUE TITLE
Settings: Website accessibility preferences

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#627] opened 2022-08-03 16:23 UTC
- [x] #628
- [x] #629
- [x] #630

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2265%3A74852

**Comment by greatislander** [comment] 2022-08-03 17:37
Duplicate of #494.

**Closed** 2022-08-03 17:39 UTC
Labels: enhancement
